# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#

# Some configuration settings cannot be changed for GitHub Pages sites.
#
#   https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll#configuring-jekyll-in-your-github-pages-site
#

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
github: [ metadata ]

locale: fr
# title_separator         :     #default [" | "]
# subtitle                : "Chulapa Jekyll Theme starter pack"    #default [your-repository-tagline]
# description             : "Chulapa Jekyll Theme starter pack" #default [your-repository-tagline]
# url                     :     #See baseurl - On Github Pages you may leave it blank - If you use CNAME use your domain
# baseurl                 :     #On Github Pages you may leave it blank. Have a look to: https://byparker.com/blog/2014/clearing-up-confusion-around-baseurl/
# words_per_minute        :     #default[200]
# timezone                :     #"Europe/Madrid ,see https://jekyllrb.com/docs/configuration/options/ and https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Build settings
# theme: minima
remote_theme: "dieghernan/chulapa"
chulapa-skin:
  skin: deeply

# Some plugins are installed by default for GitHub Pages sites.
#
#   https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll#plugins
#
plugins:
- jekyll-feed
- jekyll-github-metadata
- jekyll-include-cache
- jekyll-sitemap
- jekyll-remote-theme
- jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
- .sass-cache/
- .jekyll-cache/
- gemfiles/
- Gemfile
- Gemfile.lock
- node_modules/
- LICENSE
- README.md
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/

# HTML Compression
# - https://jch.penibelst.de/
compress_html:
  clippings: all
  blanklines: true

title: Personal blog
subtitle: Rahenda's personal blog
description: >- # this means to ignore newlines until "baseurl:"
  Rahenda's contribution spans from tech industry in semiconductor and telecommunications to associative world. He is always eager to make impact. His motto is something.
author:
  name: Rahenda
  avatar: https://github.com/rahendatri.png
  location: Paris, FR
  links:
  - url: https://github.com/rahendatri
    icon: "fab fa-github"
    label: "View on Github"
  - url: test@mail.mail
    icon: far fa-envelope
    label: "My personal email"

# Defaults https://jekyllrb.com/docs/configuration/front-matter-defaults/
defaults:
- scope:
    path: ""
  values:
    layout: "default"
    header_type: "base"
    include_on_search: false
    cloudtag_url: "/tags" #This is where the link on tags would redirect
    cloudcategory_url: "/categories" #This is where the link on categories would redirect
- scope:
    path: ""
    type: "posts"
  values:
    header_type: "post"
    include_on_search: true
    include_on_feed: true
    show_date: true
    show_bottomnavs: true
    show_sociallinks: true
    show_comments: true
    show_tags: true
    show_categories: true
    show_author: true

# Navbar https://dieghernan.github.io/chulapa/docs/02-config
navbar:
  style: fab
  brand:
    title: Home
    # img: "./assets/img/site/brand-clear.png"
    url: /
  nav:
  - title: About me #Label
    url: /about #url
  - title: Two-level link #Label
    child:
    - title: Second level first item
      url: /url2-1
    - title: Second level second item
      url: /url2-2
